# Generated by Django 3.1.1 on 2020-09-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='profile_permissions', to='current.Permission'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='current.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='role_permissions', to='current.Permission'),
        ),
    ]
