# Generated by Django 3.1.1 on 2020-09-15 15:55

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('is_inheritable', models.BooleanField(default=False)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, unique=True), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, unique=True), size=None)),
                ('roles', models.ManyToManyField(blank=True, related_name='roles', to='proposed.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
