# Generated by Django 3.1.1 on 2020-09-15 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, unique=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, unique=True), null=True, size=None),
        ),
    ]
