# Generated by Django 3.1.1 on 2020-09-15 18:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposed', '0002_auto_20200915_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, unique=True), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, unique=True), blank=True, default=[], size=None),
        ),
    ]
